### ISSUE TITLE
Create Welcome Page

### ISSUE THREAD

**Issue by bhighlander** [bhighlander/INDIVIDUAL-ASSESSMENT-vocab-YOU-lary#2]
**User Story:**
As a user, I want to see a welcome page when I first visit Vocab-YOU-Lary that displays "Welcome to Vocab-YOU-Lary" and a login button, so that I can easily access the login page and begin using the app.

**Acceptance Criteria:**

- When I visit Vocab-YOU-Lary for the first time, I see a welcome page with the heading "Welcome to Vocab-YOU-Lary" and a login button.
- Clicking the login button opens the login popup.

**Dependencies:**

- Navbar should be functional and display on the page

**Dev Notes:**

- The welcome page can be created using HTML, CSS, and JavaScript.
- The login button should be styled in a way that makes it clear and easy to click.

**Comment by leonn00albert** [comment]
I can take this one

**Comment by leonn00albert** [comment]
do you have any other design requirements?

**Comment by bhighlander** [comment]
@leonn00albert i appreciate the offer! this is an assignment for school, however, and is a solo project.
